#!/bin/bash
# Generates the hack/kind-e2e-values.yaml file with specified image versions.
# This file is NOT checked in - it's generated at build time.
set -o errexit

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPERATOR_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROJECT_ROOT="$(cd "${OPERATOR_ROOT}/.." && pwd)"
VALUES_FILE="${SCRIPT_DIR}/kind-e2e-values.yaml"

# Read version from VERSION file
DEFAULT_VERSION="$(cat "${PROJECT_ROOT}/VERSION" 2>/dev/null || echo "dev")"

# Default versions (use VERSION file if not overridden)
OPERATOR_TAG="${OPERATOR_TAG:-${DEFAULT_VERSION}}"
AGENT_TAG="${AGENT_TAG:-${DEFAULT_VERSION}}"
LITELLM_VERSION="${LITELLM_VERSION:-v1.56.5}"
OLLAMA_TAG="${OLLAMA_TAG:-latest}"
REGISTRY="${REGISTRY:-kind-local}"

cat > "${VALUES_FILE}" << EOF
# Helm values for KIND E2E testing
# Generated by hack/update-kind-e2e-values.sh - do not edit manually
#
# Images are loaded via 'kind load docker-image' so imagePullPolicy: IfNotPresent works

controllerManager:
  manager:
    image:
      repository: ${REGISTRY}/kaos-operator
      tag: ${OPERATOR_TAG}
    imagePullPolicy: IfNotPresent

defaultImages:
  agentRuntime: ${REGISTRY}/kaos-agent:${AGENT_TAG}
  mcpServer: ${REGISTRY}/kaos-mcp-server:${AGENT_TAG}
  litellm: ${REGISTRY}/litellm:${LITELLM_VERSION}
  ollama: ${REGISTRY}/ollama:${OLLAMA_TAG}

# Enable Gateway API for E2E tests
gatewayAPI:
  enabled: true
  createGateway: true
  gatewayName: kaos-gateway
  gatewayClassName: envoy-gateway
  listenerPort: 80
EOF

echo "Generated ${VALUES_FILE}"
